version: '2'
services:
  database:
    image: postgres:9.6.1
    restart: always
    env_file:
      - dev.env
    volumes:
        - database:/var/lib/postgresql/data
  app:
    image: registry.gitlab.propulsion-home.ch/greenteamagician/django-social-app:master
    restart: always
    env_file:
      - prod.env
    depends_on:
      - database
    command: 'sh /scripts/run.sh'
    volumes:
      - database:/database

  nginx:
    image: nginx:latest
    volumes:
      - run:/run
      - static-files:/static-files
      - media-files:/media-files
      - ./gnginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    command: /bin/bash -c "nginx -g 'daemon off;'"

volumes:
  database:
  static-files:
  media-files:
  run:
