version: '3'
services:
  app:
    image: registry.gitlab.propulsion-home.ch/full-stack/solutions/week-2/day-5/rest-flask-api:latest
    restart: always
    environment:
      - FLASK_APP=app.py
    command: ["sh", "/app/scripts/run.sh"]
    volumes:
      - /run:/run
      - database:/database

volumes:
  database:
