# Generated by Django 2.0.3 on 2018-03-23 10:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0009_auto_20180322_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='share_relation',
            field=models.TextField(null=True, verbose_name='share_relation'),
        ),
        migrations.AlterUniqueTogether(
            name='dislike',
            unique_together={('user', 'post')},
        ),
    ]
