# Generated by Django 2.0.3 on 2018-03-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_auto_20180323_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=200, null=True, verbose_name='email_userprofile'),
        ),
    ]
