# Generated by Django 2.0.3 on 2018-03-26 10:04

from django.db import migrations, models
import project.feed.models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0012_userprofile_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='registration',
            field=models.CharField(default=project.feed.models.code_generator, max_length=15, unique=True,
                                   verbose_name='registration_code'),
        ),
    ]
