# Generated by Django 2.0.3 on 2018-03-26 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0013_auto_20180326_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='registration',
            new_name='registration_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
    ]
