# Generated by Django 2.0.3 on 2018-03-26 14:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0015_auto_20180326_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(related_name='friends', to=settings.AUTH_USER_MODEL, verbose_name='friends'),
        ),
        migrations.AlterField(
            model_name='post',
            name='share_relation',
            field=models.TextField(null=True, verbose_name='share_relation'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
