# Generated by Django 2.0.3 on 2018-03-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0016_auto_20180326_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sprichwort',
            field=models.CharField(max_length=150, null=True, verbose_name='sprichwort'),
        ),
    ]
