# Generated by Django 2.0.3 on 2018-03-29 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0020_auto_20180327_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STATUS', models.CharField(choices=[('ACCEPTED', 'accepted'), ('PENDING', 'pending'), ('DECLINED', 'declined')], max_length=200)),
                ('friend_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_user', to=settings.AUTH_USER_MODEL, verbose_name='friend_user')),
                ('my_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='my_user')),
            ],
        ),
        migrations.DeleteModel(
            name='Friends',
        ),
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
