# Generated by Django 2.0.3 on 2018-03-29 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0021_auto_20180329_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='STATUS',
            field=models.CharField(choices=[('ACCEPTED', 'accepted'), ('PENDING', 'pending'), ('DECLINED', 'declined')], default='ACCEPTED', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together={('my_user', 'friend_user')},
        ),
    ]
